# Generated by Django 4.2.5 on 2023-09-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PVE',
            fields=[
                ('id', models.IntegerField(max_length=240, primary_key=True, serialize=False, verbose_name='PVE_ID')),
                ('title', models.CharField(max_length=20, verbose_name='PVE_Title')),
                ('lvlMax', models.IntegerField(verbose_name='PVE_LvlMax')),
                ('currentLvl', models.IntegerField(verbose_name='PVE_CurrentLvl')),
                ('exp', models.IntegerField(verbose_name='PVE_Exp')),
            ],
        ),
    ]
